### PR TITLE
1. transfer all style to "if" statement

### PR DESCRIPTION
**Pull request by vladymyrkon**
Hi. While the modular approach is necessary to connect a file for each module to access the mixins, which leads to unnecessary code.
This
`html[data-v-0d1b3c9c] {
  font-size: 100%;
}
body[data-v-0d1b3c9c] {
  margin: 0;
  padding: 0;
  line-height: 1.5;
}`
generated for each module.

### CODE REVIEW

**Comment by ianrose** [comment]
@vladymyrkon Hi, thanks for the pull-request. To have _Typesettings_ set type on the baseline the `html` element requires to have the font-size be set by _Typesettings'_ vars and the `body` line-height also set by _Typesettings'_ vars. Without those rulesets if one were to use _Typesettings'_ functions and mixins the type (outputted CSS math) would not be on the baseline.

Would you be able to share the Sass that is outputting your example CSS and your project setup?

**Comment by vladymyrkon** [comment]
@ianrose, ty for answer :) Yes, i understood it, but what if i want to use only mixins? I setup a vue project and in vue styles of component are isolated. In case of use external library i need include it to every file where i want to use it. May be worthwhile to break it up into multiple files, how do u think? And then it will be possible include base styles for `body` and `html` in general file and include only mixins in scoped files.
Sorry for my english.

**Comment by ianrose** [comment]
I think I get it now 👍. Give me a few and I'll spin up what I think would be non-breaking solution.

**Comment by ianrose** [comment]
@vladymyrkon take a look: https://github.com/ianrose/typesettings/pull/44

**Comment by ianrose** [comment]
@kondratenkoVladymyr https://github.com/ianrose/typesettings/releases/tag/v4.0.0

**Pull request closed without merging**
